#!/bin/sh

sxhkd &
clipit &
xsetroot -cursor_name left_ptr &

nm-applet --sm-disable &
wal -s -i ~/.local/share/wallpaper2.jpg
~/.config/polybar/polybar.sh &
#dropbox start
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

(alacritty -e tmux new-session -A -s 0 &) && (sleep 0.5 && wmctrl -r "alacritty" -t 1)
(firefox &) && (sleep 0.5 && wmctrl -r "firefox" -t 0)
