#!/bin/sh

sxhkd &

nm-applet --sm-disable &
wal -i /home/mota/.local/share/wallpaper2.jpg
~/.config/i3/polybar.sh &
#dropbox start
dunst &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         1
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

(konsole -e tmux new-session -A -s 0 &) && (sleep 0.5 && wmctrl -r "konsole" -t 1)
(firefox &) && (sleep 0.5 && wmctrl -r "firefox" -t 0)
