#!/bin/bash

if [ -x "$(command -v sxhkd)" ]; then
  sxhkd &
fi

#if [ -x "$(command -v clipit)" ]; then
#  clipit &
#fi

# set cursor to be arrow instead of 'x'
xsetroot -cursor_name left_ptr &

if [ -x "$(command -v nm-applet)" ]; then
  nm-applet --sm-disable &
fi

if [ -x "$(command -v pasystray)" ]; then
  pasystray &
fi

if [ -x "$(command -v blueman-applet)" ]; then
  blueman-applet &
fi

bg="$HOME/.local/share/wallpaper2.jpg"

if [ -x "$(command -v wal)" ]; then
  wal -s -i $bg
else
  if [ -x "$(command -v feh)" ]; then
    feh --bg-scale --zoom fill $bg
  fi
fi

if [ -f ~/.config/polybar/polybar.sh ]; then
  ~/.config/polybar/polybar.sh &
fi

#if [ -x "$(command -v dropbox)" ]; then
  #dropbox start
#fi

if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

# bspc monitor -d I II III IV V VI VII VIII IX X

for m in $(xrandr -q | grep -w connected | awk '{print $1}'); do
    bspc monitor $m -d $m/{1..10}
done

bspc config border_width              1
bspc config window_gap                12
bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config top_padding               15
bspc config bottom_padding            0
bspc config -m HDMI-2 top_padding     0
bspc config -m HDMI-2 bottom_padding  15

# moves workspaces to active monitor
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Peek desktop='^1' state=floating follow=on
bspc rule -a \*:"FuzzyLauncher" state=floating center=on sticky=on
bspc rule -a \*:"FloatingTerminal" state=floating center=on sticky=on

if [ -x "$(command -v wmctrl)" ]; then
  if [ -x "$(command -v alacritty)" ]; then
    (alacritty -e tmux new-session -A -s 0 &) && (sleep 0.5 && wmctrl -r "alacritty" -t 1)
  fi

  if [ -x "$(command -v firefox)" ]; then
    (firefox &) && (sleep 0.5 && wmctrl -r "firefox" -t 0)
  fi
fi
